name: Deploy to GitHub Pages

# master ブランチに対する PR が merge された時のみ実行される
on:
  pull_request:
    branches:
      - master
    types: [closed]
    paths-ignore:
      - './roro/date.json' # date.json 自身の変更ではトリガーしない

jobs:
  build:
    if: |
      github.repository == 'roratorio-hub/ratorio' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードを取得
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Node.js のセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # memo: version 22 のEOLは 2027年4月頃

      # Node.js 依存関係をインストール & webpack でビルド
      - name: Install and build Node.js dependencies
        working-directory: workspace
        run: |
             npm install
             npm run build
             npx ts-node --project tsconfig.node.json utils/yamlMergeAndCompress.ts

      # PR に release ラベルが付与されている時のみ PR がマージされた日時を json に書き出す
      - name: Get and format PR merged date in JST
        if: contains(github.event.pull_request.labels.*.name, 'release')
        id: get_formatted_pr_date
        working-directory: workspace
        run: |
          LATEST_PR_DATE_UTC="${{ github.event.pull_request.merged_at }}"
          FORMATTED_JST_DATE=$(node -e "
            const { format } = require('date-fns');
            const { toZonedTime } = require('date-fns-tz');
            const utcDate = new Date('$LATEST_PR_DATE_UTC');
            const jstDate = toZonedTime(utcDate, 'Asia/Tokyo');
            const formattedDate = format(jstDate, 'yyyy-MM-dd HH:mm');
            console.log(formattedDate);
          ")
          echo "{\"release_date\": \"$FORMATTED_JST_DATE\"}" > ../roro/date.json

      # PR に release ラベルが付与されている時のみ json をコミットする
      - name: Commit and push if changed
        if: contains(github.event.pull_request.labels.*.name, 'release')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./roro/date.json
          git commit -m "リリース日時の更新"
          git push

      # `dist` ディレクトリの内容を GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # ルートディレクトリをコピーする
          exclude_assets: '.circleci,.github,.gemini,node_modules,.gitignore,解析メモ,util,workspace'
